#!/usr/bin/env python3
"""Filter noise from a unified diff before it is shown to review agents.

Matches the rules ported from ci-pr-review-system:
- skip lockfiles, dependency manifests, generated assets, binaries, maps
- skip files whose first lines contain a generated marker (unless migrations)
- preserve migrations even if they look generated
"""
import re
import sys

NOISE_FILE_PATTERNS = [
    "bun.lock", "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "Cargo.lock", "go.sum", "go.mod", "poetry.lock", "Pipfile.lock",
    "flake.lock", ".snap",
]
NOISE_EXTENSIONS = [
    ".min.js", ".min.css", ".bundle.js", ".map", ".svg", ".png", ".jpg",
    ".jpeg", ".gif", ".ico", ".woff", ".woff2", ".ttf", ".eot",
]
GENERATED_MARKERS = [
    "// @generated", "/* eslint-disable */", "// Code generated by",
    "// GENERATED", "// AUTO-GENERATED",
]
MIGRATION_PATHS = ["migrations/", "db/migrate/", "alembic/", "migrate/"]


def is_noise_file(path):
    lower = path.lower()
    for pattern in NOISE_FILE_PATTERNS:
        if pattern in lower:
            return True
    for ext in NOISE_EXTENSIONS:
        if lower.endswith(ext):
            return True
    return False


def is_migration(path):
    return any(p in path for p in MIGRATION_PATHS)


def has_generated_marker(patch):
    first_lines = "\n".join(patch.split("\n")[:10])
    return any(marker in first_lines for marker in GENERATED_MARKERS)


def main():
    raw = sys.stdin.read()
    files = re.split(r"(?=^diff --git )", raw, flags=re.MULTILINE)
    out = []
    for f in files:
        if not f.startswith("diff --git"):
            continue
        m = re.match(r"^diff --git a/(.+?) b/(.+?)$", f, re.MULTILINE)
        if not m:
            continue
        new_path = m.group(2)
        if is_noise_file(new_path):
            continue
        if not is_migration(new_path) and has_generated_marker(f):
            continue
        out.append(f)
    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main()
